target: quality
test_size: 0.3
rf_hp:
  n_estimators: 50
  max_depth: 10
  random_state: 42
data:
  data_dir: data
  test_size: 0.3
  random_state: 42
#MLFLOW_TRACKING_URI : http://mlflow:5000
MLFLOW_TRACKING_URI : http://localhost:5000
EXPERIMENT_NAME : classification_pipeline_experiment
MODEL_NAME: classification_pipeline_model